USE TASKRABBIT_PRODUCTION.PUBLIC
;

SELECT TOP 5 * FROM PUBLIC.OPTIMIZELY_IMPRESSION_EVENTS
--WHERE EXPERIMENT_KEY LIKE '%mobile_search%';
WHERE EXPERIMENT_KEY = 'client-2021-03-01-mobile_search_page_update'
;

SELECT TOP 5 * FROM PUBLIC.OPTIMIZELY_ENR_CONV 
;
SELECT TOP 5 * FROM PUBLIC.OPTIMIZELY_DASHBOARD_RESULTS 
--WHERE EXPERIMENT_NAME = 'growth-2020-03-31-react_example_ab_test'
WHERE EXPERIMENT_NAME = 'growth-2020-04-20-mobile_example_ab_test'
;

SELECT EXPERIMENT_NAME,COUNT(*),MIN(START_TIME_UTC),MAX(END_TIME_UTC),COUNT(DISTINCT VARIATION_ID),MAX(VARIATION_ID),MIN(VARIATION_ID)
FROM PUBLIC.OPTIMIZELY_DASHBOARD_RESULTS 
GROUP BY 1
ORDER BY 3 DESC
;
SELECT 		EXPERIMENT_ID,EXPERIMENT_NAME,VARIATION_ID,VARIATION_NAME,MAX(IS_BASELINE_VARIATION) AS IS_BASELINE_VARIATION
--			,MIN(START_TIME_UTC),MAX(END_TIME_UTC),COUNT(DISTINCT VARIATION_ID),MAX(VARIATION_ID),MIN(VARIATION_ID)
FROM 		PUBLIC.OPTIMIZELY_DASHBOARD_RESULTS 
WHERE 		EXPERIMENT_NAME LIKE 'growth-%'
GROUP BY 	1,2,3,4
HAVING 		DATEDIFF(DD,MAX(END_TIME_UTC),CURRENT_DATE) BETWEEN 0 AND 1
ORDER BY 	MAX(END_TIME_UTC) DESC, EXPERIMENT_NAME DESC
;

SELECT TOP 5 * FROM PUBLIC.OPTIMIZELY_IMPRESSION_EVENTS 
;
SELECT TOP 5 * FROM PUBLIC.OPTIMIZELY_ENR_DECI 
;
SELECT TOP 5 * FROM PUBLIC.OPTIMIZELY_ENR_CONV 
;

USE TASKRABBIT_PRODUCTION.PUBLIC
;

SELECT COUNT(DISTINCT GUID) 
--;SELECT TOP 5 * 
FROM PUBLIC.OPTIMIZELY_ENR_CONV  WHERE EXPERIMENT_ID LIKE '%20078454119%' AND EVENT_NAME = 'decorated_invoice_submitted'
;

SELECT COUNT(DISTINCT GUID),MIN(CREATED_AT),MAX(CREATED_AT)
FROM PUBLIC.OPTIMIZELY_IMPRESSION_EVENTS  WHERE EXPERIMENT_KEY = 'tasker-2021-02-25-same_day_start_time_buffer'
--AND CREATED_AT >='2021-04-13'
;
--671025
SELECT VARIATION_ID,COUNT(DISTINCT GUID),MIN(CREATED_AT),MAX(CREATED_AT),COUNT(DISTINCT DATE(CREATED_AT)) AS "day_count"
--;SELECT TOP 5 * 
FROM PUBLIC.OPTIMIZELY_ENR_DECI  WHERE EXPERIMENT_ID ='20053754433' AND ENVIRONMENT='production' 
GROUP BY 1
;
--5509
SELECT COUNT(DISTINCT GUID) FROM PUBLIC.JOB_RECOMMENDATIONS WHERE CREATED_AT BETWEEN '2021-04-13' AND '2021-04-21'
;

SELECT COUNT(*) FROM PUBLIC.REACT_NATIVE_EVENTS 
WHERE CREATED_AT BETWEEN '2021-03-18' AND '2021-04-21'
AND 
;

select distinct EXPERIMENT_NAME , METRIC_EVENT_NAME 
from "PUBLIC".OPTIMIZELY_DASHBOARD_RESULTS 
where EXPERIMENT_NAME ='growth-2020-03-31-react_example_ab_test'
;



SELECT COUNT(*) FROM PUBLIC.OPTIMIZELY_ENR_DECI WHERE EXPERIMENT_ID IN 
(
SELECT EXPERIMENT_ID--,MAX(TIMESTAMP) 
FROM PUBLIC.OPTIMIZELY_ENR_DECI 
WHERE ENVIRONMENT='production'
GROUP BY 1
HAVING DATE(MAX(TIMESTAMP)) >= DATEADD(DAY,-1,DATE(CURRENT_DATE))
) 
;


SELECT	 VISITOR_ID AS "visitor_id"
		,EXPERIMENT_ID AS "experiment_id"
		,VARIATION_ID AS "variation_id"
		,GUID AS "guid"
		,ENVIRONMENT AS "environment"
		,TIMESTAMP AS "timestamp"
--;SELECT COUNT(*)
FROM PUBLIC.OPTIMIZELY_ENR_DECI 
WHERE EXPERIMENT_ID IN('20063077810','20078454119')
;
;

SELECT MAX(START_TIME_UTC) FROM PUBLIC.OPTIMIZELY_DASHBOARD_RESULTS 
;


SELECT TOP 5 * FROM PUBLIC.REACT_NATIVE_EVENTS 
;
SELECT TOP 5 * FROM PUBLIC.JOB_FLOW_EVENTS 
;

SELECT * FROM (
SELECT DISTINCT GUID AS "guid",CLIENT_PUBLISH_TYPE AS "client_publish_type",CREATED_AT AS "created_at",'web' AS "platform"
FROM PUBLIC.JOB_FLOW_EVENTS
UNION
SELECT DISTINCT GUID AS "guid",CLIENT_PUBLISH_TYPE AS "client_publish_type",CREATED_AT AS "created_at",'native' AS "platform"
FROM PUBLIC.REACT_NATIVE_EVENTS
)
WHERE "created_at" = CURRENT_DATE() 
;


SELECT TOP 10 * FROM (
;SELECT COUNT(*) FROM (
SELECT DISTINCT GUID AS "guid",CLIENT_PUBLISH_TYPE AS "client_publish_type",CREATED_AT AS "created_at",'web' AS "platform"
FROM PUBLIC.JOB_FLOW_EVENTS
--UNION
--SELECT DISTINCT GUID AS "guid",CLIENT_PUBLISH_TYPE AS "client_publish_type",CREATED_AT AS "created_at",'native' AS "platform"
--FROM PUBLIC.REACT_NATIVE_EVENTS
) WHERE "created_at" >= '2021-03-16'
;

SELECT top 5 * FROM PUBLIC.OPTIMIZELY_ENR_CONV 
;


SELECT dis
